# Shallow Net in Keras

Bulding a Shallow Neural Network to classify MNIST digits.

#### Set seed for reproducibility

In [2]:
import numpy as np
np.random.seed(42)

#### Load dependencies

In [3]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras import regularizers
from keras.callbacks import TensorBoard

/opt/conda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


#### Load data

In [4]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 6s 0us/step


In [5]:
X_train.shape

(60000, 28, 28)

In [6]:
y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [7]:
X_test[0]
y_test[0]

7

In [8]:
y_test.shape

(10000,)

In [9]:
X_test.shape

(10000, 28, 28)

#### Preprocess data
Flatten and normalise input data.

In [10]:
X_train = X_train.reshape(60000, 28 * 28 * 1).astype('float32')
X_test = X_test.reshape(10000, 28 * 28 * 1).astype('float32')

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
# One-hot encoded categories
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_train[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### Design Neural Network architecture

In [15]:
# Initialiser: zeros; random_uniform; glorot_uniform; and he_uniform.
# Regularisers: L2; and Dropout

model = Sequential()
model.add(Dense(64, activation = 'sigmoid', input_shape = (28 * 28 * 1,),
                kernel_initializer='random_uniform'))
model.add(Dense((10), activation = 'softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


#### Configure model

In [17]:
model.compile(loss = 'mean_squared_error', optimizer = SGD(lr=0.01), metrics = ['accuracy'])

#### Train!

In [18]:
model.fit(X_train, y_train, batch_size = 128, epochs = 5, verbose = 1, validation_split = 0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/5
54000/54000 [==============================] - 1s 25us/step - loss: 0.0916 - acc: 0.0921 - val_loss: 0.0911 - val_acc: 0.1008
Epoch 2/5
54000/54000 [==============================] - 1s 22us/step - loss: 0.0909 - acc: 0.1054 - val_loss: 0.0905 - val_acc: 0.1157
Epoch 3/5
54000/54000 [==============================] - 1s 22us/step - loss: 0.0904 - acc: 0.1339 - val_loss: 0.0901 - val_acc: 0.1757
Epoch 4/5
54000/54000 [==============================] - 1s 22us/step - loss: 0.0900 - acc: 0.2134 - val_loss: 0.0897 - val_acc: 0.2608
Epoch 5/5
54000/54000 [==============================] - 1s 22us/step - loss: 0.0896 - acc: 0.2751 - val_loss: 0.0894 - val_acc: 0.3047


#### Test Predictions

In [19]:
predictions = model.predict_classes(X_test, verbose = 2)
print(predictions)

[4 5 1 ... 7 1 0]


#### Test Final Accuracy

In [20]:
final_loss, final_acc = model.evaluate(X_test, y_test, verbose = 1)
print("Final loss: {0:.4f}, final accuracy: {1:.4f}".format(final_loss, final_acc))

10000/10000 [==============================] - 0s 30us/step
Final loss: 0.0894, final accuracy: 0.2894
